import Head from "next/head";
import React from "react";
import { useState, useEffect } from "react";
import { getReserves } from "../components/config";
import { SusdChart } from "../components/susd-chart";

export default function Reserves() {
  const [reservesInfo, storeReserves] = useState([]);

  useEffect(() => {
    const updateStats = setInterval(() => {
      getCollaterals();
    }, 1000);
    return () => clearInterval(updateStats);
  }, [reservesInfo]);

  useEffect(() => {
    counterNum();
  }, [reservesInfo]);

  async function getCollaterals() {
    const output = await getReserves();
    let colla = output.rsvamounts[0];
    let collb = output.rsvamounts[1];
    let susdsup = output.susdsupply;
    const reservesInfo = [
      {
        coinLogo: "tether.png",
        colA: "USDT",
        colAsupply: colla,
        colB: "WETH",
        colBsupply: collb,
        total: susdsup,
      },
    ];
    storeReserves(reservesInfo);
  }

  async function counterNum() {
    const counters = document.querySelectorAll(".value");
    const speed = 400;

    counters.forEach((counter) => {
      const animate = () => {
        const value = +counter.getAttribute("count");
        const data = +counter.innerText;

        const time = value / speed;
        if (data < value) {
          counter.innerText = Math.ceil(data + time);
          setTimeout(animate, 1);
        } else {
          counter.innerText = value.toLocaleString();
        }
      };

      animate();
    });
  }

  return (
    <div className="backstyle reservesbackground">
      <Head>
        <title>GsDeX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="reserveshero">
        <div className="py-4">
          <h1
            className="text-center"
            style={{
              fontFamily: "SF Pro Display",
              fontSize: "1.8rem",
              fontWeight: "600",
              color: "#fff",
            }}
          >
            Gs Stable Reserves
          </h1>
        </div>
        <div className="d-flex justify-content-center mb-5">
          <div
            className="card col-lg-9 p-0"
            style={{
              border: "none", // Add this line to remove the border
              borderRadius: "15px",
            }}
          >
            <div className="p-6">
              <SusdChart />
            </div>
          </div>
        </div>
        <div className="text-center mb-4">
          <h2
            style={{
              fontWeight: "bold",
              color: "white",
              fontSize: "1.5rem",
            }}
          >
            Live Reserves Stats
          </h2>
        </div>
        {reservesInfo.map((col, i) => (
          <div key={i} className="d-flex justify-content-center mb-4">
            <div
              className="card text-center col-lg-3 mx-1 p-0 reservesstats"
              style={{
                backgroundColor: "rgba(57, 255, 20, 0.16)",
                borderRadius: "15px",
                boxShadow: "0px 0px 20px rgba(0, 0, 0, 0.3)",
              }}
            >
              <div className="p-4">
                <img
                  className="mx-auto"
                  src={col.coinLogo}
                  width="120"
                  style={{ opacity: "0.8" }}
                  alt="Coin Logo"
                />
                <a target="_blank" href="">
                  <h6
                    className="mt-3"
                    style={{
                      fontFamily: "SF Pro Display",
                      fontSize: "1rem",
                      color: "white",
                    }}
                  >
                    Vault Contract
                  </h6>
                </a>
              </div>
            </div>
            <div
              className="card text-center col-lg-2 mx-1 p-0 reservesstats"
              style={{
                backgroundColor: "rgba(57, 255, 20, 0.16)",
                borderRadius: "15px",
                boxShadow: "0px 0px 20px rgba(0, 0, 0, 0.3)",
              }}
            >
              <div className="p-4">
                <p className="card-header" style={{ color: "white" }}>
                  {col.colA}
                </p>
                <div className="mt-3">
                  <h4
                    className="reservesvalues value"
                    count={col.colAsupply}
                    style={{ color: "white" }}
                  >
                    0
                  </h4>
                </div>
              </div>
            </div>
            <div
              className="card text-center col-lg-2 mx-1 p-0 reservesstats"
              style={{
                backgroundColor: "rgba(57, 255, 20, 0.16)",
                borderRadius: "15px",
                boxShadow: "0px 0px 20px rgba(0, 0, 0, 0.3)",
              }}
            >
              <div className="p-4">
                <p className="card-header" style={{ color: "white" }}>
                  {col.colB}
                </p>
                <div className="mt-3">
                  <h4
                    className="reservesvalues value"
                    count={col.colBsupply}
                    style={{ color: "white" }}
                  >
                    0
                  </h4>
                </div>
              </div>
            </div>
            <div
              className="card text-center col-lg-4 mx-1 p-0 reservesstats"
              style={{
                backgroundColor: "rgba(57, 255, 20, 0.16)",
                borderRadius: "15px",
                boxShadow: "0px 0px 20px rgba(0, 0, 0, 0.3)",
              }}
            >
              <div className="p-4">
                <p className="card-header" style={{ color: "white" }}>
                  Total Supply
                </p>
                <div className="mt-3">
                  <h4
                    className="reservesvalues value"
                    count={col.total}
                    style={{ color: "white" }}
                  >
                    0
                  </h4>
                </div>
              </div>
            </div>
          </div>
        ))}
      </main>
    </div>
  );
}
